version: '3.8'

services:
  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  node-service:
    build: ./docker/api
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - node-service

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
